### ISSUE TITLE
Support for Form Validation like Angular2 Forms

### ISSUE THREAD

**Issue by faizanahemad** [Caballerog/ng2-inline-editor#1]
Need unsuported directives like `pattern` for form validation, also support for custom validation function would be great addition.

**Comment by Caballerog** [comment]
I have started to migrate the package to angularRC5 and forms 0.3.0. The first feature that I will integrate in the new version will be the `pattern` in the `input text`.

**Comment by Caballerog** [comment]
I've upgrade ng2-inline-edit with this features: `pattern `and `fnErrorPattern` (933883d0369c01050a2064022f1e6491c8ca3797). You can read the example of the documentation.
