### ISSUE TITLE
Support for a placeholder text which is not the default text when editing

### ISSUE THREAD

**Issue by tomsun** [Caballerog/ng2-inline-editor#11]
When a field is empty you might want to draw attention to it by adding a descriptive placeholder text, which when clicked should open the inline editor.

If I use the `empty` attribute for this purpose, the placeholder text is also the default value, which is undesired sometimes. Any suggestions?

https://github.com/Caballerog/ng2-inline-editor#empty-components

## Example

```
        <inline-editor
          type="text"
          empty="No name set"
          [(ngModel)]="user.name"
          (onSave)="updateName($event)"></inline-editor>
```

![ng2-inline-editor](https://cloud.githubusercontent.com/assets/442510/19408308/51761fea-92c2-11e6-814d-5d2c1f4b382a.png)
![ng-inline-editor-editing](https://cloud.githubusercontent.com/assets/442510/19408310/55aa755c-92c2-11e6-8094-ca4a71a3c596.png)

**Comment by Caballerog** [comment]
That's a great idea, give me a few days to develop this feature.

;-)

**Comment by Caballerog** [comment]
I just to updated to 0.1.1-alpha.8, which I've develop this feature. So, you can try it!

**Comment by tomsun** [comment]
Awesome! thank you! :-)

---

I'm a bit confused by the terminology though: 

Did you originally intend `empty` to mean `default display value` or `default edit value` or both? 

- `empty` had both meanings in `0.1.1.-alpha.7` (example above).
- in `0.1.1.-alpha.8`, `empty` seems to be `default display value` only (example below).

Is it still possible to provide a `default edit value` somehow? I don't need to currently, but someone might...


### Examples

Based on the names I tried this first, to test which part of its functionality `empty` retained vs `placeholder`

```
        <inline-editor *ngIf="authService.currentUser.mayEditName(user)"
          type="text"
          placeholder="No name set"
          empty="Joe"
          [(ngModel)]="user.name"
          (onSave)="updateName($event)"></inline-editor>
```

With this result

![ng2-inline-editor-3](https://cloud.githubusercontent.com/assets/442510/19410747/4bb05b40-92fc-11e6-8cb4-2e247753ebf2.png)
![ng2-inline-editor-3b](https://cloud.githubusercontent.com/assets/442510/19410748/4eb443ce-92fc-11e6-9e7d-3da723386e50.png)

I.e. I guessed empty would still pre-fill the edit field - but I was wrong; empty is now only a `default display value`

My original snippet on the other hand does exactly what I need.

You hooked up the placeholder to a greyed out thing - didn't even think of that idea, nice! Not strictly needed in my example, I'm happy as long as the `default edit value` can be set to "" so that the user doesn't have to undo any characters, while showing something descriptive before you enter edit mode.

```
        <inline-editor
          type="text"
          empty="No name set"
          [(ngModel)]="user.name"
          (onSave)="updateName($event)"></inline-editor>
```
![ng2-inline-editor-4](https://cloud.githubusercontent.com/assets/442510/19410788/2f431226-92fd-11e6-9ce6-3ba38dd18c11.png)
![ng2-inline-editor-4b](https://cloud.githubusercontent.com/assets/442510/19410792/3ab91af6-92fd-11e6-9e9a-743e93f2be03.png)

Will someone miss the ability to set the `default edit value`? Or is it possible some other way that I missed?

Cheers!

**Comment by Caballerog** [comment]
Hi @tomsun,

> I'm a bit confused by the terminology though:
> 
> Did you originally intend empty to mean default display value or default edit value or both?
> 
> empty had both meanings in 0.1.1.-alpha.7 (example above).
> in 0.1.1.-alpha.8, empty seems to be default display value only (example below).
> Is it still possible to provide a default edit value somehow? I don't need to currently, but someone might... 

That's true, I've changed the mean of empty and placeholder in this version like you said.

About your question, you can set the default edit value from TS, for example:

my-component.html
```
   <inline-editor
          type="text"
          empty="No name set"
          [(ngModel)]="user.name"
          (onSave)="updateName($event)"></inline-editor>
```

my-component.ts
```

private user : User = new User();
user.name = 'myDefaultValue'; 
```

Is this your question?

Thanks for your comments :-)

**Comment by tomsun** [comment]
Good :-) 

(Can be difficult to distingusih between user intent vs default, if you have to assign the default to the model upfront in that scenario. Perhaps you can get around it by relying on whether onSave has fired or not)

**Comment by Caballerog** [comment]
@tomsun That's a good idea too. I must to refactoring and include testing in the module because it's more large each day. I going to thinking about your comment.
