### ISSUE TITLE
ng2 final

### ISSUE THREAD

**Issue by nottinhill** [Caballerog/ng2-inline-editor#13]
Does your Code work with ng2 final? You write RC5 and later, but as the whole community is more than aware right now, final did break every conceivable dependency on RC5. Any plans to update your code to ng2-2.0.0,  2.1.0-rc1 or even 2.1.0 ?

**Comment by Caballerog** [comment]
Yes, this code work with Angular 2.0.0 and I think that could work with 2.1.0 (I've been reading the changes and any new feature break the behaviour of this module).

In this moment, I'm using the module in a ng2-final project. My plan is included new components and features in the next weeks and update to the last angular2 version in each iteration.
