### ISSUE TITLE
The basic demo fails to compile

### ISSUE THREAD

**Issue by igncp** [Caballerog/ng2-inline-editor#14]
Hi,

I did a clean `npm i` in the basic demo, then a `npm start`, which uses `ng serve` and it is throwing some errors, complaining about the format of the config file `angular-cli.json`. I tried with a similar configuration as the other demo, but it still fails. I am using node 6.3.0, and the other dependencies should come from the `package.json`. Can you build it with a clean `npm i`?

Thanks!

**Comment by Caballerog** [comment]
Thanks @igncp  for the PR, I just to test the new version which works perfectly.
