### ISSUE TITLE
typings: not found

### ISSUE THREAD

**Issue by Ellipizle** [Caballerog/ng2-inline-editor#16]
This module keeps on failing on my build system with the following errors
`10:08:24.279 npm ERR! Failed at the ng2-inline-editor@0.1.1-alpha.8 postinstall script 'typings install'.`

**Comment by BartNetJS** [comment]
+1

**Comment by Caballerog** [comment]
@Ellipizle  you willl need to install typings as global first.

`npm install typings -g`

It should probably be documented or automatically installed when you first run npm install, any ideas?

**Comment by igncp** [comment]
I think the issue could be in that the `typings` package is currently a `devDependency` and not a `dependency`, so it is not installed when a user includes `ng2-inline-editor` as a dependency. I would guess that if it is moved to `dependencies`, when running `typings install`, first it would look in `./node_modules/.bin/typings` (relative to the `ng2-inline-editor` dir). However to try it a version with `typings` as a dependency would have to be published and then installed in an environment without `typings` in the global packages.
