### ISSUE TITLE
Docs not updated with Angular 2.0 ?

### ISSUE THREAD

**Issue by ManojkumarMuralidharan** [Caballerog/ng2-inline-editor#17]
<inline-editor type="text" [(ngModel)]="editableText"></inline-editor>

this gives us 

Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'inline-editor'.
1. If 'inline-editor' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'inline-editor' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by ManojkumarMuralidharan** [comment]
My bad, I think i forgot to add the Forms Module. I was able to get it working once I added it as suggested by[ Gabriele Ciech
](http://stackoverflow.com/questions/38892771/cant-bind-to-ngmodel-since-it-isnt-a-known-property-of-input)

**Comment by Caballerog** [comment]
Thanks @ManojkumarMuralidharan for your comment :-)
