### ISSUE TITLE
Demos in GitHub Pages

### ISSUE THREAD

**Issue by igncp** [Caballerog/ng2-inline-editor#2]
Hi,

I am practicing a little bit with Angular2 at the moment, saw your project today and it looks interesting. However, it would be nice to have the two demos (or if you add more in the future) in GitHub pages so it would be faster to try. The site would be http://caballerog.github.io/ng2-inline-editor, and it only requires a `gh-pages` branch in the current repo with the static files. Would you consider a pull request in the following days which would do the following?

- Adds a githook `postcommit` which checks the git diff of the demos directory, and if it is not empty...
- It changes to the `gh-pages` branch and generates a bundle for each demo, commits it, and changes back to the `master` branch again

I saw that you use `webpack` there so it should be straightforward. If you give the ok, my only comments would be that in my PR:
- the script would be written in bash (it would not work in Windows)
- the index page where it lists the demos would be really simple, just a list using basic bootstrap (you could improve it later)
- the demos would have to work without a server. I see that one demo uses `sockjs-node` to retrieve the json, which I am not familiar with and I might have to change.

Please let me know what do you think, the main problem I see would be the third point (not being able to use a dynamic server for the demos)

Cheers

**Comment by igncp** [comment]
Just saw more closely to the gif of the `Readme.md` and it seems you are using Windows. Unfortunately I am not familiar with Windows PowerShell so an alternative would be a bash script file that could be run from time to time, instead of a githook which runs always. But I understand that it would probably not be very convenient.

**Comment by Caballerog** [comment]
Hi @igncp,

> Hi,
> I am practicing a little bit with Angular2 at the moment, saw your project today and it looks interesting. However, it would be nice to have the two demos (or if you add more in the future) in GitHub pages so it would be faster to try. The site would be http://caballerog.github.io/ng2-inline-editor, and it only requires a gh-pages branch in the current repo with the static files. Would you consider a pull request in the following days which would do the following?

Of course, that sounds great! I never have use gh-pages :-)
> 
> Adds a githook postcommit which checks the git diff of the demos directory, and if it is not empty...
> It changes to the gh-pages branch and generates a bundle for each demo, commits it, and changes back to the master branch again
> I saw that you use webpack there so it should be straightforward. If you give the ok, my only comments would be that in my PR:
> 

Perfect for me.

> the script would be written in bash (it would not work in Windows)

I love *NIX system, for years that I do not have Windows on my computer.

> the index page where it lists the demos would be really simple, just a list using basic bootstrap (you could improve it later)

Ok.

> the demos would have to work without a server. I see that one demo uses sockjs-node to retrieve the json, which I am not familiar with and I might have to change.
> Please let me know what do you think, the main problem I see would be the third point (not being able to use a dynamic server for the demos)

I use angular-cli to run the demos. We can generate a build version of the demos which don't require any server: `ng build --prod`
> 
> Cheers

Cheers!

**Comment by igncp** [comment]
Cool! I'll create the PR in a few days
