### ISSUE TITLE
Possibility to clear field from code?

### ISSUE THREAD

**Issue by leetal** [Caballerog/ng2-inline-editor#20]
So, it seems that somehow the values get saved in the editable field, and this messes up the model if i'm for example changing the model from a component.

See GIF for example:
![error](https://cloud.githubusercontent.com/assets/1221839/20130543/bf4d1872-a657-11e6-8ec9-e9781e8c6f5e.gif)

In the GIF, whenever i press the green button, the model gets nulled out to default values.

Is this an unfortunate bug or a direct fault on my side?
Is there any way of emptying the inputfield from code upon for example a save of the data?

**Comment by Caballerog** [comment]
Hi @leetal,

Would you to do a little plunkr? Or there's any method that I could see your code?

It could be a bug, I'm not sure because I should to do specs in the future.

**Comment by leetal** [comment]
I'll write a simple plunkr later today/evening to demonstrate the issue 👍

**Comment by Caballerog** [comment]
Hi @leetal, 

Thanks very much. I'll fix the bug when I detect it because I've never had this use case ;-)
