### ISSUE TITLE
ERROR in InlineEditorModule is not an NgModule

### ISSUE THREAD

**Issue by jsphweid** [Caballerog/ng2-inline-editor#25]
I can't past the basic example. I run `ng init` using Angular CLI, then `npm i ng2-inline-editor --save`. Add `import {InlineEditorModule} from 'ng2-inline-editor';` to app module then in the same file add `InlineEditorModule` to the imports array and ng serve that up and I get that `ERROR in InlineEditorModule is not an NgModule` error. I saw your note on various versions of Angular2 ruining compatibility and so I copied your package.json from one of your examples, re-ran the `ng serve` and got the same error.

Any ideas?

**Comment by xxxtonixxx** [comment]
Hi @jsphweid , there is a problem with latest angular-cli and typescript ([angular-cli issue](https://github.com/angular/angular-cli/issues/3426)). [This could help you](http://stackoverflow.com/questions/41420619/error-appmodule-is-not-an-ngmodule)
