### ISSUE TITLE
AOT mode is not supported

### ISSUE THREAD

**Issue by Eolan** [Caballerog/ng2-inline-editor#33]
I use AOT with systemjs and I have some troubles with your component.

Basically I used the following procedure to be able to use it in aot mode:
https://github.com/yuyang041060120/angular2-ui-switch/issues/2
... and got it working to until the following error:

Error at [...]/node_modules/ng2-inline-editor/dist/inline-editor.component.ngfactory.ts:1434:46: Property 'editing' is private and only accessible within class 'InlineEditorComponent'.

Witch basically means you're probably accessing a private property of your component from inside the html file... My guess is that you just need to use a getter instead. 

Thx

**Comment by Caballerog** [comment]
I just upload a new version which AOT is supported :-)
