### ISSUE TITLE
fnErrorLength issue with minification in angular-cli

### ISSUE THREAD

**Issue by devakone** [Caballerog/ng2-inline-editor#37]
Hello,
Great module you got here, I ran into some edge cases that I think are worth looking into.

Let's say I define my input as:

`<inline-editor  empty="Add Text" #intro type="textarea" [(ngModel)]="intro.text" (onSave)="saveText($event)"
					(onEdit)="editText($event)" (onCancel)="cancel($event)" min="5" [fnErrorLength]="onTextMissing"> </inline-editor>`

And the onTextMissing is defined in the component like this:

`onTextMissing = () => {
    this.isTextMissing = true;
  }`

I am using the closure because i need to reference a binding in my component. This renders the following HTML
`<inline-editor _ngcontent-ljw-49="" empty="Add Text" min="5" type="textarea" _nghost-ljw-43="" ng-reflect-empty="Add text " ng-reflect-type="textarea" ng-reflect-min="5" ng-reflect-fn-error-length="function () {
            _this.isTextMissing = true;
        }" class="ng-untouched ng-pristine ng-valid">`

This works fine in dev mode, but when it builds for production the ` ng-reflect-fn-error-length` attribute never makes it to the HTML. I am using the angular-cli so it might be something in the webpack build.

**Comment by xxxtonixxx** [comment]
Hi @devakone , can you provide us a demo? Thanks for your report!

**Comment by devakone** [comment]
Never mind, this was due to the fact that I was using Anmgulr 2.1 at the time when the code for this library had been updated to be compatible with 2.3 and above. I had to revert momentarily to an earlier version of this library before finally updating it. You can go ahead and close this. Thank you.

**Comment by xxxtonixxx** [comment]
Thank you for your feedback! :+1:
