### ISSUE TITLE
Control visibility of the input

### ISSUE THREAD

**Issue by devakone** [Caballerog/ng2-inline-editor#38]
The `editing` variable is private in the component, but in case I want to control validation of the input there is no way to do so atm.
Adding a public `setEditMod(mode:boolean)` variable would help transfer control of the visibility of the editor to the calling component.

**Comment by xxxtonixxx** [comment]
Thanks for your feedback!

**Comment by xxxtonixxx** [comment]
This feature will be added with #57 using the method `edit( { editing: boolean, doFocus: boolean } )` 👍

**Comment by xxxtonixxx** [comment]
This should be fixed in the last version (`0.2.0-alpha.0`). With the change of name, you should do an `npm i @qontu/ngx-inline-editor` and update your imports 👍
