### ISSUE TITLE
Unexpected value 'InlineEditorModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by alvirtuoso** [Caballerog/ng2-inline-editor#39]
Anybody had this problem?

> Unexpected value 'InlineEditorModule' imported by the module 'AppModule'.

in my app.module.ts:
`import { InlineEditorModule } from 'ng2-inline-editor';

...
@NgModule({
  imports: [InlineEditorModule, ...],
  declarations: [...]
`

in my template:
` <inline-editor type="text" [(ngModel)]="editableText" (onSave)="saveEditable($event)" name="editableText1" size="8"></inline-editor>`

I installed using npm: 

> npm i ng2-inline-editor --save

Did I miss anything?

**Comment by devakone** [comment]
What version of Angular are you using? And it sounds like you are more than likely using the angular-cli? This is a known issue when you're using a new version of the cli than the one this project was targeted at.

**Comment by Caballerog** [comment]
Today we've pushed a new version which is compatible with ng4. In the next day, I going to publish a new release in npm's repository.

**Comment by MorlaRamakrishna** [comment]
I am facing the same issue (alvirtuoso facing issue) with the inline editor, my angular version is 2.4.7, could you suggest me how to solve this?
