### ISSUE TITLE
ng build error with AOT compiler

### ISSUE THREAD

**Issue by Shallyin83** [Caballerog/ng2-inline-editor#43]
I am getting below error in ng build --prod.
----------------------------------------------------
ERROR in /Volumes/Working/projects/test/src/$$_gendir/node_modules/ng2-inline-editor/dist/inline-editor.co
mponent.ngfactory.ts (334,18): Property 'container' is private and only accessible within class 'InlineEditorCo
mponent'.
/Volumes/Working/projects/test/src/$$_gendir/node_modules/ng2-inline-editor/dist/inline-editor.component.n
gfactory.ts (380,42): Property 'editing' is private and only accessible within class 'InlineEditorComponent'.
/Volumes/Working/projects/test/src/$$_gendir/node_modules/ng2-inline-editor/dist/inline-editor.component.n
gfactory.ts (390,47): Property 'editing' is private and only accessible within class 'InlineEditorComponent'.

ERROR in /Volumes/Working/projects/test/src/$$_gendir/node_modules/ng2-inline-editor/dist/inputs/input-tex
tarea.component.ngfactory.ts (152,48): Property 'rows' does not exist on type 'InputConfig'.
/Volumes/Working/projects/test/src/$$_gendir/node_modules/ng2-inline-editor/dist/inputs/input-textarea.com
ponent.ngfactory.ts (157,49): Property 'cols' does not exist on type 'InputConfig'.

**Comment by Caballerog** [comment]
It's a priority for us. I the next days we hope release a ng4 compatible version.

**Comment by Caballerog** [comment]
We've pushed a new version which is ng4 compatible. In the next day we going to integrated this version in our projects and publish the new npm binary release.
