### ISSUE TITLE
Unexpected value 'InlineEditorModule' imported by the module 'NewreconAppModule'

### ISSUE THREAD

**Issue by MorlaRamakrishna** [Caballerog/ng2-inline-editor#45]
This issue closed but I am facing the same issue with angular 2
Could you guys help me to sort out this?

Anybody had this problem?

Unexpected value 'InlineEditorModule' imported by the module 'AppModule'.
in my app.module.ts:
`import { InlineEditorModule } from 'ng2-inline-editor';

...
@NgModule({
imports: [InlineEditorModule, ...],
declarations: [...]
`

in my template:
<inline-editor type="text" [(ngModel)]="editableText" (onSave)="saveEditable($event)" name="editableText1" size="8"></inline-editor>

I installed using npm:

npm i ng2-inline-editor --save
Did I miss anything?

**Comment by xxxtonixxx** [comment]
@MorlaRamakrishna  I have't had that problem... 

Can you try the latest version if that problem has been fixed?
