### ISSUE TITLE
alpha 20 break styling

### ISSUE THREAD

**Issue by otusweb** [Caballerog/ng2-inline-editor#60]
In alpha 19, the styling had by default a red underlined text
<img width="434" alt="screen shot 2017-05-19 at 10 58 27" src="https://cloud.githubusercontent.com/assets/1069914/26240685/257f7d22-3c82-11e7-8554-90557097afd1.png">

With version alpha 20: 
the text has no styling making it hard to see that user can click.

also the html generated seem to be missing some divs:
alpha 19:

`<inline-editor _ngcontent-c3="" empty="Slide key takeaway" min="0" name="tweetText" size="140" type="text" _nghost-c2="" class="ng-untouched ng-pristine ng-valid"><div _ngcontent-c2="">
                <div _ngcontent-c2="" id="inlineEditWrapper">
                    <a _ngcontent-c2="" class="editable-empty">Slide key takeaway</a>
                    <div _ngcontent-c2="" class="inlineEditForm form-inline" hidden="">
                        <div _ngcontent-c2="" class="form-group">                          
                            <div _ngcontent-c2=""></div><inline-editor-text _nghost-c4="" ng-version="4.0.3"><input _ngcontent-c4="" class="form-control ng-untouched ng-pristine ng-valid" type="text" placeholder="" size="140"></inline-editor-text>
                            <span _ngcontent-c2="" class="inline-editor-button-group">
                                <button _ngcontent-c2="" class="btn btn-xs btn-primary" id="inline-editor-button-save"><span _ngcontent-c2="" class="fa fa-check"></span></button>
                                <button _ngcontent-c2="" class="btn btn-xs btn-danger"><span _ngcontent-c2="" class="fa fa-remove"></span> </button>
                            </span>
                            </div>
                        </div>
                    </div>
               </div></inline-editor>`

(sorry for poor formatting could not figure what is wrong)

vs alpha 20:
` <inline-editor _ngcontent-c2="" empty="Slide key takeaway" min="0" name="tweetText" size="140" type="text" class="ng-untouched ng-pristine ng-valid"><div>   <div id="inlineEditWrapper">     <a class="editable-empty c-inline-editor">Slide key takeaway</a>     <div class="c-inline-editor inlineEditForm form-inline" hidden="">       <div class="form-group">         <div></div><inline-editor-text _nghost-c3=""><input _ngcontent-c3="" class="form-control ng-untouched ng-pristine ng-valid" type="text" placeholder="" size="140"></inline-editor-text>         <span class="c-inline-editor inline-editor-button-group">          <button class="btn btn-xs btn-primary c-inline-editor" id="inline-editor-button-save"><span class="fa fa-check"></span></button>         <button class="btn btn-xs btn-danger c-inline-editor"><span class="fa fa-remove"></span> </button>         </span>        </div>     </div>   </div> </div></inline-editor>`

**Comment by xxxtonixxx** [comment]
We have decoupled styling from component. That styles are located in `ng2-inline-editor/themes/bootstrap.css` and you can import them 👍

**Comment by xxxtonixxx** [comment]
If you use angular-cli, you can import them using this line in `src/styles.css`:
```scss
@import '~ng2-inline-editor/themes/bootstrap.css'
```

**Comment by Caballerog** [comment]
You would create your own styles and themes. If you're using `angular-cli` you can use SASS (`.scs`s) in your transpiler.

In the next release I going to put a class to the inputBase container which you would style the display. At the moment it's `display:block`.

**Comment by otusweb** [comment]
ok, thx
