### ISSUE TITLE
HTML in textarea?

### ISSUE THREAD

**Issue by twmiller** [Caballerog/ng2-inline-editor#7]
HTML tags rendered inside of a text area when it's in the non-edit mode?

For instance, if my textarea is`<p>Chunk of text.</p>` it's rendering as `<p>Chunk of text.</p>` in both display mode and edit mode, instead of formatting based on the tags.

**Comment by twmiller** [comment]
My temporary solution for this was to change:

`<a>{{ value }}</a>`

to 

`<a [innerHTML]="value"></a>` in the template section of the inline-editor-component js file.

**Comment by Caballerog** [comment]
Yes, It could be an option in the configuration of the component. If you want you can send the PR with the improve. Thanks!

**Comment by Caballerog** [comment]
I've been thinking about HTML in textarea and I believe that could be a good idea add ck-editor how a new element.

**Comment by Caballerog** [comment]
I've think about this issue, would be a good option use ngx-quill (https://github.com/KillerCodeMonkey/ngx-quill)
