### ISSUE TITLE
Angular 2.0

### ISSUE THREAD

**Issue by OleksiiZubko** [Caballerog/ng2-inline-editor#8]
Hi, Thanks for the library. Can we use angular 2.0 to develop this lib?

Best,

**Comment by OleksiiZubko** [comment]
Perfect, thanks!

**Comment by Caballerog** [comment]
I just to updated to Angular 2.0.0 (The lib worked perfectly before this commit ee125128e64efc29bf1554107e1f2debe6c26083)
