### ISSUE TITLE
Support 'empty' for select inputs

### ISSUE THREAD

**Issue by peloncano** [Caballerog/ng2-inline-editor#9]
I am trying to display a inline-editor of type `select` to edit entities with missing values. I need the dropdown to display even when the value of the bound `ngModel` does not exist within the `options` data collection. This seems to work well for type `text` where it displays the link of `empty` if it is empty. Similar functionality should be added to `select`. As of now you can't edit select field unless it has a matching option value.

**Comment by Caballerog** [comment]
This is a good idea. This feature will be implement soon.

**Comment by peloncano** [comment]
@Caballerog - thanks - looking forward to it.

**Comment by bmudda** [comment]
+1 I think this an important feature for dropdowns that are not just boolean fields

**Comment by Caballerog** [comment]
Hi @peloncano, @bmudda  I've been developing this feature, but I've any questions:

1. Do you want to send this options object?
```
data: [
      { id: 1, field: 'status1Incomplete' },
      { field: 'status2' },
      { id: 3, field: 'status3Incomplete' },
      { field: 'status4Incomplete' }
    ],
    value: 'id',
    text: 'field'
  }
```
Where some elements are not "value" field. 
2. So, when you select i.e status2 you're not relation this text with any value, it's ok?

**Comment by peloncano** [comment]
Hey @Caballerog,
Thanks for looking into this. What I was referring to is having the inline-editor display an `empty` string (string should be editable) if the `ngModel` value assign is not found within any of the HTML select options' values.

I was looking at the code an in `ng2-inline-editor/src/inline-editor.component.ts` line 47 you have a call to a method called `optionSelected()`

```
<a [ngClass]="{'editable-empty': isEmpty }"  (click)="edit(value)" [hidden]="editing"> {{optionSelected()}} </a>
```

I'm thinking that the `optionSelected()` should return the `empty` string if value not available in select input.

Now the select should also probably handle or allow for an empty value to be set. We can do this by passing an empty value and text or an option within the inline-editor component; something like `allowEmpty` boolean, which would automatically add the empty option at the beginning of the select.

The select's data will most of the time need the `value` and the `text`

**Comment by bmudda** [comment]
@Caballerog 
I agree with @peloncano suggestion. And per @peloncano comment 

> The select's data will most of the time need the `value` and the `text`

I personally think the option data should always have `value`/`text` pair (`id`/`field` based on your sample above). Except when a user wants to clear the selection completely and send back an empty value to the save() method. The empty option could be implemented as @peloncano suggested above.

**Comment by Caballerog** [comment]
@peloncano  @bmudda I just updated the module to ng2-inline-editor.alpha-6 (933904e). I hope that it be useful for you!

**Comment by peloncano** [comment]
@Caballerog thanks for this. Seems to be working. The only issue I noticed is that you committed a lot of console.logs which is spitting a lot of logs into the developer tools.

**Comment by Caballerog** [comment]
@peloncano Oh.. I thinked that I had removed the console.log (One moment and I fix it! :-))

**Comment by bmudda** [comment]
@Caballerog thanks for the fix and update. This is a really great module.

**Comment by peloncano** [comment]
@Caballerog thanks for removing the console.logs! Hoping to see the `In Progress` features completed in the near future! 👍
